### ISSUE TITLE
Resolving of resources from /lang not working properly if playing with other than the /Default database

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1219] opened 2024-11-11 03:46 UTC
Steps to reproduce:

* Clone the `/Default` folder into something else, like `/Other`
* In `config/settings.xml`, change the `databaseDir` to `res/database/Other`
* Change something in `res/database/Other/lang/de`, e.g. the name of `1994aa3a-23c3-48ce-b20a-d1f021df8c63` "Königin Svetlana" from "von Schweden" to "von Dänemark"
* Start a new game, which will now use the `Other` database. Other changes will work. However, when getting the programme `a61e7775-7565-48cd-ab4a-e5faea09d70d`, "VHS im Test", "Königin Svetlana" will still appear as "von Schweden" instead of "von Dänemark".

So, either the `lang` folder is ignored here, or it's still read from `Default`.

**Comment by nittka** [comment] 2024-11-11 07:33
probably still read from default

**Comment by nittka** [comment] 2024-11-12 15:11
The issue is not quite trivial. The lang resources are not part of the saved game but are loaded on demand. A quick fix would be to store the database base path in the save game, so that the correct resources are used when loading.

Sharing a savegame will not be 100% compatible because there is no guarantee for the same resources being present (in the same location), but the situation is not worse.
A refactoring making the lang-files part of the saved database is out of scope, for now.

**Closed** 2024-12-01 14:57 UTC
Labels: bug
