### ISSUE TITLE
Lower left TV breaks when switching off and on again

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1044] opened 2023-10-31 01:16 UTC
"Have you tried switching it off and on again?"

Sure, but that's exactly when the TV breaks indefinitely.

The TV just remains off, and can't be switched on again.
*However*, when hovering over the channel buttons, the TV picture for that program will still be shown. Which may be an additional bug, I'm not sure.

Even after saving and reloading a game, the situation is still the same.

Should be easily reproducible, seems the functionality is broken in general. If not, I'll provide the savegame.

Just astonishing that no-one reported this feature. Who ever needs to switch off the TV after all? I wondered about that "feature" that you can switch off the TV at all already back then in Mad TV. What's the purpose? Less distraction so you can "focus" better? `:)`

**Comment by nittka** [comment] 2023-10-31 14:23
So far, I cannot reproduce the problem (Linux). For a newly started game turning the TV on/off does not break the hover (note that switching on is not done using the off-button, but using a channel button).

My assumption is that even a savegame might not help. I don't know if I can make myself clear. The savegame does not contain absolutely all data and not all game status is persisted and taken from that data. That is, if something is broken internally and not "repaired" by loading the game, it remains broken (e.g. maybe the broken hover for the TV). Likewise, not everything broken is transferred to the savegame. So maybe the hover status is not persisted and loading in a freshly started game will not have the problem anymore.

**Comment by GWRon** [comment] 2023-10-31 17:21
The channel tooltip is only visible when the game is not "paused".

If the game is not paused the game logic for "button reaction" is a simple check of the "mouse position" (for hover) and "click" (for activation)

Maybe that "paused" thing is what borks it for @scr0llbaer9000

**Comment by scr0llbaer9000** [comment] 2023-11-03 12:22
> clicking on a channel button (not the power button) and it stays on again

But not when clicking the power button, right?

Is there a misunderstanding here?

The expectation is absolutely that, just as in real life, when you switch the TV off with the main black power button, you can also switch it on again with the black button (as was the case in Mad TV afair). And I figure it is still reproducible that this doesn't work?

I indeed was wrong in OP that the TV was broken "indefinitely", as it can be switched on again by clicking on one of the channel buttons. For some reason it didn't dawn on me to try that. `:)`

**Comment by GWRon** [comment] 2023-11-03 12:34
I might have remembered wrong about old TVs... But for me they are simply 5 "switches". Press one and the others are deactivated.
So power off will switch off other buttons too etc.

Of course this can be changed. Guess that code is around 15 yrs old now ;-)

**Comment by scr0llbaer9000** [comment] 2023-11-03 12:48
yeah the 4 channel buttons can be switches, but the power button is its own thing.

When switching on with the power button, the last "active" channel can be shown again.
(In real life, channel buttons on most TVs weren't switches either though, the last "state" was not remembered, and channel 1 was shown when switching on.)

**Comment by nittka** [comment] 2023-11-04 05:59
For simplicity, my suggestion would be to show the channel of the "active" player when switching on, again.

**Closed** 2023-11-05 13:02 UTC
