### ISSUE TITLE
Modal popup warning where there should be an in-game non-modal

### ISSUE THREAD

**Issue by jez9999** [TVTower/TVTower#1120] opened 2024-04-18 16:01 UTC
I was putting stuff into my programme planner and I got a modal popup:

> Ronny: Du hattest Programme/Werbung im Programmplan die als nicht programmiert deklariert waren.

Presumably this should be a localized in-game popup instead?  The offending code is at https://github.com/TVTower/TVTower/blob/master/source/game.screen.programmeplanner.bmx#L1993

**Comment by GWRon** [comment] 2024-04-18 17:42
This indicates that something happened which should not happen at all. I had it in in the hope to not see it again ;-)

Can you replicate it (new game or savegame)?

**Comment by jez9999** [comment] 2024-04-18 19:21
Yes.  Start a new Infinite game.  Go to the film guy and buy a film of 2 blocks length.  Schedule it for 23:00 (and 0:00 the next day).  Go to 2. day schedule.  Shift-click it, and place it at 01 hours.  Click back to go to 1.day and the msg pops up.

**Comment by GWRon** [comment] 2024-04-18 19:55
Ok, so the issue is not the placement at "01 hours" but the "shift click" at an element beginning the day before.
When shift clicking on a "normal time slot" programme you will see that a copy is created and the original programme stays at the slot.
but for this "over midnight programme" the original programme vanishes.


Will have to investigate. Thanks for the report.

**Comment by jez9999** [comment] 2024-04-18 22:04
Actually I think it's any click, not just shift-click.  I can also get the bug by just clicking and moving the show to 01:00.

**Comment by GWRon** [comment] 2024-04-18 22:12
as you see a fix is already put online but needs testing.

If you want to test too, you could give "compile it on your own" a try.
- Download a "weekly build" of BlitzMax NG : https://github.com/bmx-ng/bmx-ng/releases 
- Download the TVTower sources - in this case from the PR (branch is https://github.com/TVTower/TVTower/tree/fix_programmeplanner_overnight)
- unzip the BlitzMax NG download
- go into the folder and start MaxIDE
- open "TVTower.bmx"
- in MaxIDE menu: "Program" -> "Build Options" uncheck "Debug build" (except you want a less smooth but error-catching build :D)
- in the same menu check "Quick Build" (so only changes in modules, game code, ... will be recompiled)
- click the "flying rocket" icon or menu entry "Program -> Build and Run"
- wait a moment for the initial build (next builds will be way faster)
- the final TVTower.Win32 (or so).exe will start (you can manually start this file then without MaxIDE too)

**Comment by jez9999** [comment] 2024-04-18 23:19
Hmm.  Well I built it but the app just popped up EXCEPTION_ACCESS_VIOLATION with the debug output being:

```
[00:15:07] INFO     | CORE: Starting TVTower, v0.8.2 Build "19.04.24 00:15".
[00:15:07] LOAD     | TEVENTMANAGER.INIT(): OK
[00:15:08] DBG      | SOUNDMANAGER.SETAUDIOENGINE(): initialized with engine "AUTOMATIC [AUTOMATIC]".
[00:15:08] DBG      | PLAYMUSICORPLAYLIST: GetMusicStream from Playlist "menu" not possible. No Playlist.
[00:15:08] DBG      |                    : Music not found. Using random from default playlist
[00:15:08] DBG      |                    : could not start activeMusicChannel: no next music found
[00:15:08] DBG      | GRAPHICSMANAGER.INITGRAPHICS(): Initializing graphics.
[00:15:08] DBG      |                               : SetGraphicsDriver "OpenGL".
[00:15:08] DBG      |                               : Initialized graphics with "OpenGL".
[00:15:08] DBG      |                               : Initialized virtual graphics (for optional letterboxes).
[00:15:08] DBG      | APP.CREATE(): Loading base resources.
```

I also can't find any way to set a breakpoint in MaxIDE.

**Comment by GWRon** [comment] 2024-04-19 05:45
I will replicate in a VM today (when at the computer again)

If a debug build EAVs then the error happens "so to say" outside of blitzmax code. It happens in a external library or the generated c code.

Some weeks ago I fixed a similar issue with regards to the graphics driver selection ...so it uses sdlrender2d instead of our classic opengl backend.
Will have to look if you need an additional step to do...or if I missed something somewhere.


Breakpoints are set manually with "debugstop" in the code (other editors might add things for you assistantly). They are compiled into the binary. So no hot-debug-addRemove while running.

Am 19. April 2024 01:19:24 MESZ schrieb Jez ***@***.***>:

**Comment by GWRon** [comment] 2024-04-19 06:15
Idiot me .... the linked issue of myself already tells you - that I did that on Windows (mean receiving the segfault).

So please do as described above and replace the sdl.mod/sdl.mod folder with the older one of that specific commit (just before the sdl.mod/sdl.mod stuff got updated).

**Comment by GWRon** [comment] 2024-04-19 10:55
[sdl.mod.zip](https://github.com/TVTower/TVTower/files/15039235/sdl.mod.zip)
This is the sdl.mod (with "downgraded" (internal)sdl.mod) I use on Windows.

Download, extract, rename "blitzmax/mods/sdl.mod" to "blitzmax/mods/sdl.mod_backup" and then move in the sdl.mod-folder you just extracted.
Folder should look like this (truncated):
![image](https://github.com/TVTower/TVTower/assets/2625226/ed86cf42-64d7-4c1a-b00f-3a01fa530520)

**Comment by jez9999** [comment] 2024-04-19 12:46
Ah, it uses SDL?  So how come you guys use BlitzMax for this, out of interest?  It looks like there's some relatively popular C# bindings to SDL2 with SDL2-CS.  Gotta admit I'd be much happier in VS than in MaxIDE when debugging.  ;-)

That modified sdl.mod worked and it now builds OK.

**Comment by GWRon** [comment] 2024-04-19 12:52
I meanwhile found the issue with the current module (a custom patch to unregister sdl threads for our blitzmax modules too was missing). So if the fix is merged the next weekly build of sunday should "work out of the box" again.

SDL is just one of the underlaying libraries BlitzMax NG uses. The language itself was originally compiled/translated into assembler and then binaries. But with NG (so a decade ago) it transpiles into C. With NG also new modules/libraries were added - one of them is the (optional) replacement of some core and extended functionality by utilizing the SDL library (eg to allow more platforms to be targeted).

On top of everything there is my "dig framework" adding stuff like ingame gui functionality, graphics backend handling, sound systems, ... this is written in C and BlitzMax

And On top of this then there is the game specific code , written in Lua (AI) and BlitzMax code.
For development one could also use "Visual Studio Code" and the BlitzMax extension - but yeah, language server still missing (userbase is way way lower than with the bigger languages). But as we transpile into C I guess a lot of code would be faster than with C# (which I have to code with in my day job). It is also way easier for beginners to see some "results" and get things working.

**Comment by jez9999** [comment] 2024-04-19 13:31
Built it with the fix_programmeplanner_overnight branch and it does seem to fix the problem.

**Closed** 2024-04-26 15:06 UTC
Labels: bug, In Progress, Confirmed
