### ISSUE TITLE
Live shows with relative date shouldn't be available as live anymore after `year_relative_max`

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#1258] opened 2024-12-12 18:42 UTC
The live show "Blau Bembelsche - Best of" is defined as

`<releaseTime year_relative="2" day="3" hour="20" year_relative_min="1980" year_relative_max="1995" /> <!-- TODO: shouldn't be live anymore after 1995 -->`

It's based on a "real" show so its staff won't be not around forever, however it's defined with a relative date to make it flexible enough for that piece of content to still be available when starting to play in a wider variety of years.

After `year_relative_max` however, it definitely can't be live anymore (some of the "real" staff might not be alive anymore), but a tape version could still be around in the film agency. Right now the effect is that it is available as "live" in the film agency after 1995, but with a loss of "Aktualität", which doesn't make much sense. Either the show has to be unavailable after 1995, or it has to be a not-live taped version (which was the intention here).

(Two versions of the same show with different availability configuration would be inconvenient either, as the two versions will then exist after 1995 if a player bought and kept the first version. This is not really intended.)

**Comment by nittka** [comment] 2024-12-12 20:16
I think, at the moment there is no way to change flags (effect removeBroadcastFlag or effect addBroadcastFlag). And there is nothing in between live at a fixed time and always live (on first broadcast). The most uninvasive way (from the database definition point of view) would be to change year_relative_max to around 1990 and and restrict availability to 1995 max. If I am correct, this should make the licence available in the agency until 1995 but once it is bought, the player will keep it.

**Comment by GWRon** [comment] 2024-12-12 20:35
What you want is a kind of "live-able until timeX" thing. But if a player owns the licence you cannot change it from live to "live on tape" without giving them a "big" surprise...
 
What I do not get is, what the problem exactly is?

If a programme has a "live date" and this date passed by, it is just live on tape from that on. If you limit the release time to <1995 it should have its live date set to <1995 - if this does not work, then this is a bug.

The availability is something else - it should just decide if something eg. can be offered at the vendor at all.

**Comment by scr0llbaer9000** [comment] 2024-12-13 02:23
> exception is if it has a fixed live date ("live on next sunday 12:00")

The thing is that the example show actually has a fixed live date too. It's just the year is relative to the start year. That's all. Otherwise it's completely the same as live shows with a fixed defined year. No other difference, hence no "surprise" for the player. It's not "live when scheduled" like some other examples.

The dynamic "live when scheduled" shows could have this max year problem too, but I (think I have) removed all instances of those because of this problem (and because it wasn't *really* necessary to put a max year for those).

**Comment by nittka** [comment] 2024-12-13 15:54
I cannot quite reproduce the problem. For me, the licence is *not* available as live after 1995 (via dev-command, did not reduce offers to get it into the agency). It behaves as intended. The latest live year is correctly calculated and if that year is past, the licence is not marked as live anymore.

If you own it before the live date, it is "yellow" and once the live date is past, the live-maker disappears.

**Comment by scr0llbaer9000** [comment] 2024-12-14 01:33
It indeed now behaves as desired.

I had this issue on my TODO for a while, maybe it was fixed in the meantime, perhaps by https://github.com/TVTower/TVTower/commit/32142ba954daa500a0476fe714e76eb9f141bc34 or I had some hallucination. `:)`

The dynamic "live when scheduled" shows might still have this issue though.

**Comment by nittka** [comment] 2024-12-14 07:09
Yes, the original issue will have been affected by the change of relative year calculation.

For "live when scheduled" this issue is not restricted to year_relative_max or even programmes only. Theoretically, you could start producing your live show in 1980 and not send it until 2035 when part of the original cast could already be dead. For now, I'd simply ignore this issue.

**Closed** 2024-12-14 13:29 UTC
