### ISSUE TITLE
Names of roles aren't displayed anywhere

### ISSUE THREAD

**Issue by scr0llbaer** [TVTower/TVTower#835] opened 2023-01-14 04:56 UTC
I have a script that uses a number of defined named roles.

----

        <programmerole guid="f1fa679f-cb36-4d36-bdd7-c105b9605be4" first_name="Dink" last_name="" gender="1" />
        <programmerole guid="ac69a50f-22e0-4384-a2e4-24485b66a1ad" first_name="Chameleon" last_name="" gender="2" />
        <programmerole guid="d2168e7c-3c95-4778-b406-cb305633946a" first_name="Trint" last_name="" gender="1" />
        <programmerole guid="fbff6c7a-6795-4e2f-9a55-dd9b833945d1" first_name="Dar" last_name="" gender="1" />
        <programmerole guid="53104872-6c35-43df-a8b6-a3863db9cf9b" first_name="Isolde" last_name="" gender="2" />
        <programmerole guid="8a54557b-ded8-4427-bb60-7796c1f84317" first_name="Arturo" last_name="" gender="1" />

----

            <jobs>
                <job index="0" function="1" required="1" />
                <job index="1" function="2" required="1" gender="1" role_guid="f1fa679f-cb36-4d36-bdd7-c105b9605be4" />
                <job index="2" function="2" required="1" gender="2" role_guid="ac69a50f-22e0-4384-a2e4-24485b66a1ad" />
                <job index="3" function="2" required="1" gender="1" role_guid="d2168e7c-3c95-4778-b406-cb305633946a" />
                <job index="4" function="2" required="1" gender="1" role_guid="fbff6c7a-6795-4e2f-9a55-dd9b833945d1" />
                <job index="5" function="2" required="1" gender="2" role_guid="53104872-6c35-43df-a8b6-a3863db9cf9b" />
                <job index="6" function="2" required="1" gender="1" role_guid="8a54557b-ded8-4427-bb60-7796c1f84317" />
                <job index="7" function="32" required="1" gender="2" />
                <job index="8" function="32" required="1" gender="1" />
            </jobs>

----

But where are those names displayed?

![Screenshot from 2023-01-14 05-48-52](https://user-images.githubusercontent.com/122231074/212455764-d3f4c6bd-70b5-419a-b76e-ea1f5360606e.png)

Also, if I don't define specify the gender redundantly also in `job`, it is ignored, and I can choose an actor of any gender in the game. It seems the reference in the `role_guid` is ignored completely.

**Comment by nittka** [comment] 2023-01-14 07:12
The gender of the role is indeed not propagated to the job. This would make sense. (Even if it is set, you can cast any person - this is not a bug but intentional. The effects of such assignments as well as casting the same person multiple times are not yet optimized.)

The role names are not automatically displayed anywhere. The idea is that this information can be used in variables. There should be an example in the database format documentation. There is also work on allowing these references in more places (see #755).

**Comment by nittka** [comment] 2023-02-01 05:42
The gender propagation issue has been fixed.

**Comment by scr0llbaer9000** [comment] 2023-02-03 13:29
So you've changed your minds?

It's fine if the gender of the role does not propagate, but then it becomes all the more important that I see the *names* of the roles, so that I know in the game which actor I'm assigning to which role in the first place, so I can decide if I use another gender for Ms Doubtfire or not. Without *either* gender *or* role name propagating, I just have a long list of empty roles to fill without any hints or information, and I'm completely lost.

**Comment by nittka** [comment] 2023-02-03 15:39
I don't quite understand. In which respect did we change our minds. My last comment meant, that I addressed the gender propagation problem (if the job does not define a gender but there is a role with gender definition, the job will use that gender). However, this may be in the PR concerning variable handling in general, so it might not be part of 0.8.1 (unless I extract that part).

I did not change my mind yet, wrt. automatically showing the role name.

**Comment by scr0llbaer9000** [comment] 2023-02-05 02:03
> In which respect did we change our minds.

On Jan 14 you wrote:

> The gender of the role is indeed not propagated to the job. This would make sense. 

Ok, I guess I misread "This would make sense", this can be read both ways.

> Even if it is set, you can cast any person - this is not a bug but intentional

I was thinking this may continue to cause confusion in the future. So maybe the `job` *should* always take on the gender of the `role` implicitly by default, because that will be the most common case by far. *If* in a particular production the `job` *must* have a different gender than the `role` (Ms Doubtfire or Monty Python style), *then* the different gender can still be specified in the `job`, "overwriting" the one in the `role`. And if we want to allow *any* gender to take on that `role`, then we can specify and "overwrite" that in the `job` with `gender="0"`. I think that would be a clean approach.

----

And role names would still be nice. `:)`

**Comment by nittka** [comment] 2023-02-05 09:30
Previously: role could be defined for job, but if the job did not define a gender, the role's gender was not used

After the changes currently in progress (and really I don't know if it is already implemented or hidden in one of the open PRs): if a job explicitly defines a gender, that will be used. If the job does not define an explicit gender (0), but the role does, the role's gender is used.
For now, I don't see the necessity for overriding with "0" - simply don't associate the job with the role. (The current implementation cannot distinguish between "gender not set" and "gender set to 0" because 0 is the default value.
Do you have roles in mind that have a definite gender, but you would cast them with any gender.

With "role names would be nice" do you mean that the role name should be displayed in the cast selection dialog? (Actor (male) - Yams Pond) Because this is the first time, I understood the ticket that way (in the initial image, I thought you only wanted to show the missing gender...)

**Comment by nittka** [comment] 2023-02-05 09:42
see #843

**Comment by GWRon** [comment] 2023-02-05 09:46
I always thought scr0llbaer wanted exactly what you wrote:
```
Actor (male) - Yams Pond
```

We could discuss if the gender of a role needs to be mentioned if differing:
```
Actor (male) - Miss RambyDamby (female)
```

or we could simply say: "hey, actors can play all kind of roles, the gender of the role does not matter."

It would only matter if the movie would raise problems with "wokeness" etc.
This would also open the can of worms regarding color of people's skin, hair, age ..

A script could contain additional information about a role. But it would mean we need to take these into account for calculation of "cast fit" etc.

```
Actor - Miss RambyDamby (female, old)
Actor - Junior Griffin (male, young)
```
Would make it way more interesting but also cumbersome to have a _good_ fit then.

Anyways this would now lead to almost "offtopic" discussions but let me add: I liked that idea and had it for years in my mind. Setting a director would add this information - the director's skill would control how many "information" is exposed. An amateur would not even be able to tell you the gender, an more experienced one the gender, masters of the director skill even stuff like "age" or heritage (must come from UK ...) ... such things.

**Comment by nittka** [comment] 2023-02-05 10:11
Yes, and I did not get it until now.
My suggestion would be to leave out the textual gender hint (in case there is a role...):
* color code of the cast
* filter is preselected to the correct gender

**Closed** 2023-02-05 12:26 UTC
