### ISSUE TITLE
Tooltip for TV bottom left not appearing anymore at some time

### ISSUE THREAD

**Issue by scr0llbaer9000** [TVTower/TVTower#943] opened 2023-03-10 05:04 UTC
When playtesting with the version built by Ronny [here](https://github.com/TVTower/Documentation/issues/18#issuecomment-1460147286) it happened at some time that the tooltip for the TV on the bottom left didn't appear anymore.

![Screenshot from 2023-03-09 18-57-55](https://user-images.githubusercontent.com/123826268/224227466-88df7135-ec99-4f3e-b147-2951e8828682.png)

It happened only once, and I guess it's very rare. But I don't know how to reproduce. I made a savegame but it wasn't reproducing that effect, the tooltip worked again after restart.

**Comment by GWRon** [comment] 2023-03-10 11:05
If this happens again: can you check if you cannot open up the ESC-Menu in that case?

the ESC-Menu thing is something rarely happening too - I even added a debug-logging for it but was not motivated enough to track it down (means trying often enough to make it fail :D).

**Comment by nittka** [comment] 2023-10-22 16:43
I have never encountered this problem. I assume the other tooltips in the lower region (audience, betty...) do not stop working at this point? Basically, they are all treated identically wrt. update and rendering...
Even if you turn off the TV, you don't get the tooltip for "turning it on again"?

**Comment by scr0llbaer9000** [comment] 2023-10-31 01:17
It happened again.

> If this happens again: can you check if you cannot open up the ESC-Menu in that case?

ESC menu is still working as usual.

>  I assume the other tooltips in the lower region (audience, betty...) do not stop working at this point?

The other tooltips in the lower center info region are working.

> Even if you turn off the TV, you don't get the tooltip for "turning it on again"?

*That* led me to another bug: https://github.com/TVTower/TVTower/issues/1044

**Comment by nittka** [comment] 2023-11-01 14:14
The error is caused by very long programme titles, e.g. "Dynamit - Das Magazin Spezial: Prince Carl und Lady Dee (5/5): Dynamit Prince Carl und Lady Dee Spezial - Schlussfolge (Block 1/1)".

If the tooltip width exceeds the screen width, the tooltip is moved to the left (base.framework.tooltip line 154). There is no guard that the resulting x position remains positive. And possibly the calculation of the delta is also buggy, because with x-position 41, tooltip width 830 and screen width 800 the resulting tooltip x-position after moving is -3839.

Potential TODOs:
* check and possibly fix calculation of tooltip-deltas
* improve framework, so that original x-position is stored and is restored if title/content change (moving tooltip is only temporary)
* tooltip title is single line, so programme tooltip should possibly ensure the title passed has a maximum length

**Comment by GWRon** [comment] 2023-11-01 16:07
While this of course is a bug in the framework I have to ask: 
> "Dynamit - Das Magazin Spezial: Prince Carl und Lady Dee (5/5): Dynamit Prince Carl und Lady Dee Spezial - Schlussfolge (Block 1/1)"

Seriously? I mean ... seriously? Titles should be way way shorter - so that the ellipsis (...) does not cut away important parts and the title is still distinguishable from other elements of that series/franchise.

**Comment by nittka** [comment] 2023-11-01 16:34
I guess the length of the title is due to it's being a series episode. I would not extend the framework to allow multi-line tooltip headers! This is an absolute border case. Ensuring that the tooltip does not permanently disappear from the screen should be enough. (Making sure the resulting x coordinate is not smaller than 0 and restoring it to its original value should be enough).

**Comment by scr0llbaer9000** [comment] 2023-11-03 12:18
> Seriously? I mean ... seriously? Titles should be way way shorter - so that the ellipsis (...) does not cut away important parts and the title is still distinguishable from other elements of that series/franchise.

Yeah sure that is redundant in that case here and can be shortened.

But in general, such long titles (especially in series when combining general and episode title) can exist.

**Closed** 2023-11-06 17:52 UTC
Labels: bug
